export interface JobModel{
    joB_ID: string,
    orG_NAME: string,
    ranK_START: number,
    ranK_END: number,
    title: string,
    sysnam: string,
    numbeR_OF: number,
    worK_PLACE_TYPE: string,
    datE_FROM: string,
    datE_TO: string,
    iS_HANDICAP: boolean,
    iS_ORIGINAL: boolean,
    iS_LOCAL_ORIGINAL: boolean,
    iS_TRANSFER: boolean,
    iS_TRANING: boolean,
    worK_QUALITY: string,
    worK_ITEM: string,
    worK_ADDRESS: string,
    contacT_METHOD: string,
    vieW_URL:string,
    coordinate_X: number,
    coordinate_Y: number,
    iS_XYDoubt: boolean
}

// "joB_ID": "1f3b3301-6d7f-41d9-b21f-00b9513d9612",
// "orG_NAME": "新竹市消防局",
// "ranK_START": 5,
// "ranK_END": 7,
// "title": "科員",
// "sysnam": "綜合行政",
// "numbeR_OF": 1,
// "worK_PLACE_TYPE": "新竹市",
// "datE_FROM": "2024-12-16",
// "datE_TO": "2024-12-27",
// "iS_HANDICAP": true,
// "iS_ORIGINAL": true,
// "iS_LOCAL_ORIGINAL": false,
// "iS_TRANSFER": false,
// "iS_TRANING": false,
// "worK_QUALITY": "１、具備綜合行政職系任用資格之公務人員。\n２、經銓敘審定委任第5職等以上合格實授。\n３、國內外大學土木工程或營建工程等相關科系畢業。\n４、具土木、營建工程相關公務機關工作經驗者佳。\n５、具政府採購專業人員基礎訓練及格證書者佳。\n６、熟悉電腦文書作業軟體。\n７、具汽車及機車駕照並能親自駕駛。\n８、無公務人員任用法第26條及第28條各款規定之情事者。",
// "worK_ITEM": "１、辦理本局消防廳舍各項營建及整建工程。\n２、辦理本局行政業務相關業務。\n３、臨時交辦事項。",
// "worK_ADDRESS": "新竹市西大路679號",
// "contacT_METHOD": "1.對本開缺職務有意願者，請於113年12月27日前，經由行政院人事行政總處事求人機關徵才系統「線上」應徵職缺(網址：https://web3.dgpa.gov.tw/want03front/AP/WANTF00001.ASPX)，並請繕打簡要自述。\n2.本職缺資格符合者，另行擇優通知口試，資格不符者，恕不通知亦不退件。未獲錄取者，不另行通知。本職缺視需要增列備取2名，候補期間自甄選結果確定之翌日起算3個月，並得依序遞補原公開甄選職缺或職務列等相同、性質相近之職缺為限，期滿如未經通知遞補，則自動喪失候補資格。聯絡電話：(03)5229508轉5470林小姐。",
// "vieW_URL": "https://web3.dgpa.gov.tw/want03front/ap/wantf00001_1.aspx?work_id=1131202568",
// "coordinate_X": 24.81053,
// "coordinate_Y": 120.95761,
// "iS_XYDoubt": false